// index.tsx
import React from 'react';
import Head from 'next/head';
import LowercaseConverter from './LowercaseConverter/LowercaseConverter';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Lower Case App in Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>My Lower Case App in Next.js</h1>
      <p>
        This is a simple app that converts text to lowercase, removes punctuation, and replaces spaces with hyphens.
      </p>
      <LowercaseConverter />
    </div>
  );
} 